env:
  browser: true
  es2021: true
extends:
  - svelte3
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files: '*.svelte'
    processor: 'svelte3/svelte3'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  strict: 2
